language: python
matrix:
  include:
    - name: "Py3.5 PostgreSQL9.4"
      python: "3.5"
      addons:
        postgresql: "9.4"
      env: DATABASE_URL="postgres://postgres@localhost/dmp"
    - name: "Py3.6 SQLite3"
      python: "3.6"
      env: DATABASE_URL="sqlite:///db.sqlite3"
    - name: "Py3.6 PostgreSQL9.6 XXX"
      python: "3.6"
      env: DATABASE_URL="postgres://postgres@localhost/dmp" WORK_ID_PREFIX="XXX"
      addons:
        postgresql: "9.6"
    - name: "Py3.7 PostgreSQL10"
      python: "3.7"
      env: DATABASE_URL="postgres://postgres@localhost/dmp"
      addons:
        postgresql: "10"
    - name: "Py3.8 PostgreSQL11"
      python: "3.7-dev"
      env: DATABASE_URL="postgres://postgres@localhost/dmp"
      addons:
        postgresql: "11"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - coverage run --source='music_publisher' manage.py test 
after_success: coveralls
